// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 01.08.2026, 21:17:16
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Krutoi2006/newOFFICEPEAK/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Krutoi2006/newOFFICEPEAK/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Krutoi2006/newOFFICEPEAK/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Krutoi2006/newOFFICEPEAK/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Krutoi2006/newOFFICEPEAK/plugins/**/*.{js,ts,mjs}","C:/Users/Krutoi2006/newOFFICEPEAK/composables/**/*.{js,ts,mjs}","C:/Users/Krutoi2006/newOFFICEPEAK/utils/**/*.{js,ts,mjs}","C:/Users/Krutoi2006/newOFFICEPEAK/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Krutoi2006/newOFFICEPEAK/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Krutoi2006/newOFFICEPEAK/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Krutoi2006/newOFFICEPEAK/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;