// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 06.09.2026, 01:32:46
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Krutoi2006/Desktop/newOFFICEPEAK/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Krutoi2006/Desktop/newOFFICEPEAK/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Krutoi2006/Desktop/newOFFICEPEAK/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Krutoi2006/Desktop/newOFFICEPEAK/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Krutoi2006/Desktop/newOFFICEPEAK/plugins/**/*.{js,ts,mjs}","C:/Users/Krutoi2006/Desktop/newOFFICEPEAK/composables/**/*.{js,ts,mjs}","C:/Users/Krutoi2006/Desktop/newOFFICEPEAK/utils/**/*.{js,ts,mjs}","C:/Users/Krutoi2006/Desktop/newOFFICEPEAK/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Krutoi2006/Desktop/newOFFICEPEAK/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Krutoi2006/Desktop/newOFFICEPEAK/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Krutoi2006/Desktop/newOFFICEPEAK/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;